### ISSUE TITLE
Hash output with css modules produce NaN in animation-name when using @keyframe

### ISSUE THREAD

**Issue by blephy** [webpack-contrib/css-minimizer-webpack-plugin#39]
When using css module features, and using @keyframes, some keyframes name produce an invalid hash in the related css animation name.

```scss
.signature {
  width: 80px;

  path {
    animation: draw 3.3s ease-in-out forwards;
    stroke: #fff;
    stroke-dasharray: 450;
    stroke-dashoffset: 450;
  }

  circle {
    animation: draw-circle 0.25s ease-in 1.5s forwards;
  }
}

@keyframes draw {
  to {
    stroke-dashoffset: 0;
  }
}

@keyframes draw-circle {
  from {
    fill: #fff;
    opacity: 0;
  }

  to {
    fill: #fff;
    opacity: 1;
  }
}
```

is producing this :

```css
._2f-763U9aR_m95TZkSTerd{width:80px}._2f-763U9aR_m95TZkSTerd path{animation:NaNjtcXwnmOr8f36q3l-8W 3.3s ease-in-out forwards;stroke:#fff;stroke-dasharray:450;stroke-dashoffset:450}._2f-763U9aR_m95TZkSTerd circle{animation:_2APW8yWcYXdDHglJ5UTsYC .25s ease-in 1.5s forwards}@keyframes e5jtcXwnmOr8f36q3l-8W{to{stroke-dashoffset:0}}@keyframes _2APW8yWcYXdDHglJ5UTsYC{0%{fill:#fff;opacity:0}to{fill:#fff;opacity:1}}
```

Note the `animation:NaNjtcXwnmOr8f36q3l-8W`. Should be `animation:e5jtcXwnmOr8f36q3l-8W`.

- When i do not use `css-minimizer-webpack-plugin`, the bug disapear.

- When i rename the keyframe's name from `draw` to `draw-path` for exemple, this is working well with `css-minimizer-webpack-plugin`.

>I don't think it's a `cssnano` issue, because i'm using `cssnano` preset `default` as well with postcss-loader.

You can reproduce by following this steps in this repo :

1. [Follow this steps](https://github.com/blephy/reactjs-typescript-pwa#use-svg-files) to add the `src/images/signature.svg` to [home view](https://github.com/blephy/reactjs-typescript-pwa/blob/master/src/views/home/index.tsx)
2. Just make a production build : `npm run build`
3. Launch the production server: `npm run start:prod`

See build/css/home.css result. Webpack configuration are in `config/webpack`

- Operating System: MacOSX Catalina 10.15.5
- Node Version: 12.18.3
- NPM Version: 6.14.8
- webpack Version: 4.44.2
- css-minimizer-webpack-plugin Version: 1.1.4

Issue already asked in `css-loader` repository : https://github.com/webpack-contrib/css-loader/issues/1200 and webpack repository : https://github.com/webpack/webpack/issues/11568
