### ISSUE TITLE
Border width with two values compiled into tree values

### ISSUE THREAD

**Issue by dimti** [webpack-contrib/css-minimizer-webpack-plugin#59]
- Operating System: Linux 5.10
- Node Version: v10.23.2
- NPM Version: 6.14.11
- webpack Version: 5.23.0
- css-minimizer-webpack-plugin Version: ^1.2.0

I try to optimize some border options and use of border-width with two values: `border-width: 13px 6px;`
cssnano (css-minimizer-webpack-plugin) showed me strange and incorrect result: `border-width: 13 6px 6px;`

That strange optimization work only with exists all of three style-rules: `border-width`, `border-style`, `border-right-color`

Source:
```css
div {
    border-width: 13px 6px;
    border-style: solid;
    border-right-color: transparent;
}
```

### Expected Behavior

```css
div{border-width:13px 6px;border-right:6px transparent;border-style:solid}
```

### Actual Behavior

```css
div{border-width:13px 6px 6px;border-right:6px transparent;border-style:solid}
```

### Code

https://gist.github.com/dimti/468b3793ec81d7c5b1f0f1e1669c2eb1

### How Do We Reproduce?

Source styles:

```css
div {
    border-width: 13px 6px;
    border-style: solid;
    border-right-color: transparent;
}
```

I set `horizontal` padding to `13px` and `vertical` padding to `6px` with appropriate this tutorial https://developer.mozilla.org/ru/docs/Web/CSS/border-width#%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81

Compiled data without optimizations - show me correct result: `border-width: 13px 6px;`

With optimization i'm have incorrect result: `border-width: 13px 6px 6px;`
